### ISSUE TITLE
Error building podman inside Docker container using the latest conmon. 

### ISSUE THREAD

**Issue by chengkuangan** [containers/conmon#136]
I am doing a build inside Docker container and face the following errors during build time. This is working fine with v2.0.14
COMMAND:
git clone https://github.com/containers/conmon \
&& cd conmon \
&& make \
&& make podman

ERROR:
mkdir -p bin
cc -std=c99 -Os -Wall -Wextra -Werror -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DVERSION=\"2.0.15-dev\" -DGIT_COMMIT=\""89b2478b507c6f285cd97ae8e55c85b9cafe6e81"\"  -D USE_JOURNALD=0 -o src/conmon.o -c src/conmon.c
In file included from src/conmon.c:8:0:
src/conmon.c: In function ‘main’:
src/utils.h:47:45: error: implicit declaration of function ‘strerror’ [-Werror=implicit-function-declaration]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                                             ^
src/conmon.c:53:4: note: in expansion of macro ‘pexit’
    pexit("start-pipe read failed");
    ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:53:4: note: in expansion of macro ‘pexit’
    pexit("start-pipe read failed");
    ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:53:4: note: in expansion of macro ‘pexit’
    pexit("start-pipe read failed");
    ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:63:3: note: in expansion of macro ‘pexit’
   pexit("Failed to open /dev/null");
   ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:63:3: note: in expansion of macro ‘pexit’
   pexit("Failed to open /dev/null");
   ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:67:3: note: in expansion of macro ‘pexit’
   pexit("Failed to open /dev/null");
   ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:67:3: note: in expansion of macro ‘pexit’
   pexit("Failed to open /dev/null");
   ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:74:3: note: in expansion of macro ‘pexit’
   pexit("Failed to fork the create command");
   ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:74:3: note: in expansion of macro ‘pexit’
   pexit("Failed to fork the create command");
   ^~~~~
src/conmon.c:80:59: error: implicit declaration of function ‘strlen’ [-Werror=implicit-function-declaration]
    if (!g_file_set_contents(opt_conmon_pid_file, content, strlen(content), &err)) {
                                                           ^~~~~~
src/conmon.c:80:59: error: incompatible implicit declaration of built-in function ‘strlen’ [-Werror]
src/conmon.c:80:59: note: include ‘<string.h>’ or provide a declaration of ‘strlen’
In file included from src/conmon.c:8:0:
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:94:4: note: in expansion of macro ‘pexit’
    pexit("--attach specified but _OCI_ATTACHPIPE was not");
    ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:94:4: note: in expansion of macro ‘pexit’
    pexit("--attach specified but _OCI_ATTACHPIPE was not");
    ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:103:3: note: in expansion of macro ‘pexit’
   pexit("Failed to dup over stdin");
   ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:103:3: note: in expansion of macro ‘pexit’
   pexit("Failed to dup over stdin");
   ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:105:3: note: in expansion of macro ‘pexit’
   pexit("Failed to dup over stdout");
   ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:105:3: note: in expansion of macro ‘pexit’
   pexit("Failed to dup over stdout");
   ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:107:3: note: in expansion of macro ‘pexit’
   pexit("Failed to dup over stderr");
   ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:107:3: note: in expansion of macro ‘pexit’
   pexit("Failed to dup over stderr");
   ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:118:3: note: in expansion of macro ‘pexit’
   pexit("Failed to set as subreaper");
   ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:118:3: note: in expansion of macro ‘pexit’
   pexit("Failed to set as subreaper");
   ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:142:5: note: in expansion of macro ‘pexit’
     pexit("Failed to create !terminal stdin pipe");
     ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:142:5: note: in expansion of macro ‘pexit’
     pexit("Failed to create !terminal stdin pipe");
     ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:152:4: note: in expansion of macro ‘pexit’
    pexit("Failed to create !terminal stdout pipe");
    ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:152:4: note: in expansion of macro ‘pexit’
    pexit("Failed to create !terminal stdout pipe");
    ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:166:3: note: in expansion of macro ‘pexit’
   pexit("Failed to create stderr pipe");
   ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:166:3: note: in expansion of macro ‘pexit’
   pexit("Failed to create stderr pipe");
   ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:190:3: note: in expansion of macro ‘pexit’
   pexit("Failed to block signals");
   ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:190:3: note: in expansion of macro ‘pexit’
   pexit("Failed to block signals");
   ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:202:3: note: in expansion of macro ‘pexit’
   pexit("Failed to fork the create command");
   ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:202:3: note: in expansion of macro ‘pexit’
   pexit("Failed to fork the create command");
   ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:205:4: note: in expansion of macro ‘pexit’
    pexit("Failed to set PDEATHSIG");
    ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:205:4: note: in expansion of macro ‘pexit’
    pexit("Failed to set PDEATHSIG");
    ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:207:4: note: in expansion of macro ‘pexit’
    pexit("Failed to unblock signals");
    ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:207:4: note: in expansion of macro ‘pexit’
    pexit("Failed to unblock signals");
    ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:212:4: note: in expansion of macro ‘pexit’
    pexit("Failed to dup over stdin");
    ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:212:4: note: in expansion of macro ‘pexit’
    pexit("Failed to dup over stdin");
    ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:219:4: note: in expansion of macro ‘pexit’
    pexit("Failed to dup over stdout");
    ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:219:4: note: in expansion of macro ‘pexit’
    pexit("Failed to dup over stdout");
    ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:226:4: note: in expansion of macro ‘pexit’
    pexit("Failed to dup over stderr");
    ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:226:4: note: in expansion of macro ‘pexit’
    pexit("Failed to dup over stderr");
    ^~~~~
src/utils.h:55:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: " fmt " %s\n", ##__VA_ARGS__, strerror(errno)); \
                   ^
src/conmon.c:237:5: note: in expansion of macro ‘pexitf’
     pexitf("Invalid LISTEN_PID %.10s", listenpid);
     ^~~~~~
src/utils.h:57:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: " fmt ": %s\n", log_cid, ##__VA_ARGS__, strerror(errno)); \
                    ^
src/conmon.c:237:5: note: in expansion of macro ‘pexitf’
     pexitf("Invalid LISTEN_PID %.10s", listenpid);
     ^~~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:241:6: note: in expansion of macro ‘pexit’
      pexit("Failed to g_strdup_sprintf pid");
      ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:241:6: note: in expansion of macro ‘pexit’
      pexit("Failed to g_strdup_sprintf pid");
      ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:243:6: note: in expansion of macro ‘pexit’
      pexit("Failed to setenv LISTEN_PID");
      ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:243:6: note: in expansion of macro ‘pexit’
      pexit("Failed to setenv LISTEN_PID");
      ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:257:6: note: in expansion of macro ‘pexit’
      pexit("start-pipe read failed");
      ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:257:6: note: in expansion of macro ‘pexit’
      pexit("start-pipe read failed");
      ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:269:3: note: in expansion of macro ‘pexit’
   pexit("Failed to register the signal handler");
   ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:269:3: note: in expansion of macro ‘pexit’
   pexit("Failed to register the signal handler");
   ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:273:3: note: in expansion of macro ‘pexit’
   pexit("Failed to unblock signals");
   ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:273:3: note: in expansion of macro ‘pexit’
   pexit("Failed to unblock signals");
   ^~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:286:3: note: in expansion of macro ‘pexit’
   pexit("Failed to set handler for SIGCHLD");
   ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:286:3: note: in expansion of macro ‘pexit’
   pexit("Failed to set handler for SIGCHLD");
   ^~~~~
src/utils.h:55:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: " fmt " %s\n", ##__VA_ARGS__, strerror(errno)); \
                   ^
src/conmon.c:319:4: note: in expansion of macro ‘pexitf’
    pexitf("Failed to wait for `runtime %s`", opt_exec ? "exec" : "create");
    ^~~~~~
src/utils.h:57:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: " fmt ": %s\n", log_cid, ##__VA_ARGS__, strerror(errno)); \
                    ^
src/conmon.c:319:4: note: in expansion of macro ‘pexitf’
    pexitf("Failed to wait for `runtime %s`", opt_exec ? "exec" : "create");
    ^~~~~~
src/utils.h:47:19: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
   fprintf(stderr, "[conmon:e]: %s %s\n", s, strerror(errno)); \
                   ^
src/conmon.c:474:3: note: in expansion of macro ‘pexit’
   pexit("Failed to remove symlink for attach socket directory");
   ^~~~~
src/utils.h:49:20: error: format ‘%s’ expects argument of type ‘char *’, but argument 5 has type ‘int’ [-Werror=format=]
    syslog(LOG_ERR, "conmon %.20s <error>: %s %s\n", log_cid, s, strerror(errno)); \
                    ^
src/conmon.c:474:3: note: in expansion of macro ‘pexit’
   pexit("Failed to remove symlink for attach socket directory");
   ^~~~~
cc1: all warnings being treated as errors
Makefile:71: recipe for target 'src/conmon.o' failed
make: *** [src/conmon.o] Error 1
The command '/bin/sh -c mkdir -p $GOPATH && mkdir -p /run/systemd/journal/socket && git clone https://go.googlesource.com/go $GOPATH && cd $GOPATH && cd src && ./all.bash && cd /tmp && git clone https://github.com/containers/conmon && cd conmon && make && make podman && cp /usr/local/libexec/podman/conmon  /usr/local/bin/ && git clone https://github.com/containernetworking/plugins.git $GOPATH/src/github.com/containernetworking/plugins && cd $GOPATH/src/github.com/containernetworking/plugins && ./build_linux.sh && mkdir -p /usr/libexec/cni && cp bin/* /usr/libexec/cni && mkdir -p /etc/cni/net.d && curl -qsSL https://raw.githubusercontent.com/containers/libpod/master/cni/87-podman-bridge.conflist | tee /etc/cni/net.d/99-loopback.conf && mkdir -p /etc/containers && curl https://raw.githubusercontent.com/projectatomic/registries/master/registries.fedora -o /etc/containers/registries.conf && curl https://raw.githubusercontent.com/containers/skopeo/master/default-policy.json -o /etc/containers/policy.json && git clone https://github.com/containers/libpod/ $GOPATH/src/github.com/containers/libpod && cd $GOPATH/src/github.com/containers/libpod && make && make install' returned a non-zero code: 2

**Comment by haircommander** [comment]
thanks for the issue @chengkuangan, can you try the version in https://github.com/containers/conmon/pull/137 and let me know if it fixes it for you?

**Comment by chengkuangan** [comment]
@haircommander This works for me. The issue gone. Thanks
